# Build image for desktop utilities if it doesn't exist
exec toolbox list --images | grep desktoputilities > /dev/null || podman build --squash --tag localhost/desktoputilities:latest ~/Templates/Toolbx/DesktopUtilities
# Build container for desktop utilities if it doesn't exist
exec toolbox list --containers | grep DesktopUtilities > /dev/null || toolbox create DesktopUtilities --image localhost/desktoputilities
# Launch conky from the container
exec toolbox run --container DesktopUtilities sh -c conky -d
# exec ~/.config/conky/conky.sh
