FROM registry.fedoraproject.org/fedora-toolbox:latest
# override HOME env variable so that steam drops stuff elsewhere
RUN HOME="$HOME/Toolbox/steam"
# copy files into image
COPY root/ /
RUN chmod +x /usr/local/bin/oncreate.sh
RUN chmod +x /usr/local/bin/ondelete.sh
RUN dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
RUN dnf config-manager setopt fedora-cisco-openh264.enabled=1
RUN dnf --assumeyes install steam stow
RUN dnf clean all
