#!/bin/bash

# invoke standard bash entrypoint
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# contants

declare local dotfiles_path=~/dotfiles
declare local currentworkingdirecory=$(pwd)
declare local toolbox_default=default.interactive

cd $dotfiles_path
git ls-files --full-name --modified --others --exclude-standard | grep -i bash > /dev/null && echo Warning: untracked bash changes detected
cd $pwd

echo Entering $toolbox_default ...
toolbox list --containers | grep $toolbox_default > /dev/null || toolbox create $toolbox_defaulti
toolbox enter $toolbox_default
